/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kevin Alberto Perez
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        setSize(900,650);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        modelSubMenu1 = new com.raven.menu.ModelSubMenu();
        modelSubMenu2 = new com.raven.menu.ModelSubMenu();
        defaultSubMenuItemRender1 = new com.raven.menu.DefaultSubMenuItemRender();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        menu1 = new com.raven.menu.Menu();
        menuItem1 = new com.raven.menu.MenuItem();
        menuItem2 = new com.raven.menu.MenuItem();
        menuItem3 = new com.raven.menu.MenuItem();
        menuItem4 = new com.raven.menu.MenuItem();
        menuItem5 = new com.raven.menu.MenuItem();
        menuItem6 = new com.raven.menu.MenuItem();
        subMenuPanel1 = new com.raven.menu.SubMenuPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 25));
        setSize(new java.awt.Dimension(900, 800));
        getContentPane().setLayout(null);

        jTextPane1.setFocusable(false);
        jTextPane1.setOpaque(false);
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 670, 1280, 140);

        menuItem1.setText("menuItem1");
        menu1.add(menuItem1);

        menuItem2.setText("menuItem2");
        menuItem2.setMenuModel(new javax.swing.AbstractListModel() {
            String[] strings = { "OPPP", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menu1.add(menuItem2);

        menuItem3.setText("menuItem3");
        menu1.add(menuItem3);

        menuItem4.setText("menuItem4");
        menu1.add(menuItem4);

        menuItem5.setText("menuItem5");
        menu1.add(menuItem5);

        menuItem6.setText("menuItem6");
        menu1.add(menuItem6);

        getContentPane().add(menu1);
        menu1.setBounds(0, 0, 90, 670);

        subMenuPanel1.setForeground(new java.awt.Color(0, 51, 51));
        getContentPane().add(subMenuPanel1);
        subMenuPanel1.setBounds(80, 0, 200, 670);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Opciones");
        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.menu.DefaultSubMenuItemRender defaultSubMenuItemRender1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private com.raven.menu.Menu menu1;
    private com.raven.menu.MenuItem menuItem1;
    private com.raven.menu.MenuItem menuItem2;
    private com.raven.menu.MenuItem menuItem3;
    private com.raven.menu.MenuItem menuItem4;
    private com.raven.menu.MenuItem menuItem5;
    private com.raven.menu.MenuItem menuItem6;
    private com.raven.menu.ModelSubMenu modelSubMenu1;
    private com.raven.menu.ModelSubMenu modelSubMenu2;
    private com.raven.menu.SubMenuPanel subMenuPanel1;
    // End of variables declaration//GEN-END:variables
}
